### ISSUE TITLE
Obtaining chess_model.blend file

### ISSUE THREAD

**Issue by faizankshaikh** [georgw777/chesscog#14]
Hi - I was trying to replicate the Appendix 2.1.1 (Data Synthesis) from the paper, it mentions that the model "chess_model.blend" is not supplied. Can you tell me where I can access it?

Great work by the way!

**Comment by georg-wolflein** [comment]
Hi, thanks for your interest! Unfortunately, I don't have the .blend file anymore; it was a Blender file of the 3D chess model that I created. However, if you just want to use the dataset, there really is no need for the Blender model as the dataset itself is available online at http://doi.org/10.17605/OSF.IO/XF3KA.
