### ISSUE TITLE
Open sourcing the training data generation?

### ISSUE THREAD

**Issue by leason** [georgw777/chesscog#18]
Hey guys, thank you for sharing the link to the recently published paper (https://arxiv.org/abs/2310.04086).  I think the only practical path forward for me is to train my own model on the specific chess set my project will use.  It doesn't seem like we've cracked the problem of having a "general purpose" model that can work with any chess board in any environment.

Your solution of programmatically generating the training data seems like the most feasible way to get a great deal of data.  Do you have any plans to share the code you wrote to build the 3d model?  My thought was that it might be easier to adapt the rendering settings and load in 3d models of the pieces for different boards to regenerate the training data than it would be to either start from scratch or manually annotate pictures.

I'm assuming of course that it's possible to render a scene that is photorealistic enough for the model to be able to work on an actual photo of a chess board that matches the training model.  Have you guys tried to do that with a board that matches your 3d models?

**Comment by georg-wolflein** [comment]
It is possible to fine-tune *chesscog* to your own chess board using just two photos of the chess board in the starting position. Check out this part of the README:

> Relevant documentation is available in Appendix C.2 of my [master thesis](https://github.com/georg-wolflein/chesscog-report/raw/master/report.pdf).
> In particular, Appendix C.2.6 contains instructions for fine-tuning the model to your own chess set, using only two input images. 
> Be sure to run `python -m chesscog.transfer_learning.create_dataset` before training (a step I forgot to mention in those instructions, see [this issue](https://github.com/georg-wolflein/chesscog/issues/15).

But you are right, it doesn't seem like there's a zero-shot general-purpose model that works on any previously unseen chess set (yet -- I hope someone will make one!).

If you want to go the route of using your own synthetic training data, the code for rendering the synthetic training data using Blender is available [here](https://github.com/georg-wolflein/chesscog/blob/master/scripts/synthesize_data.py). Unfortunately, I lost the 3D Blender model I created for this project so I couldn't supply that for you.

**Comment by leason** [comment]
That is great - I have a more standard chess set on the way from house of
staunton that I think will be easier for the computer to read than my old
wood set that lacks a lot of contrast and board markers.  Will let you
know.

Congrats on a really fantastic thesis, btw.  I'm very hopeful your work
will allow me to build my chess playing buddy app!

**Comment by leason** [comment]
Ok, I got my new chess set delivered and have been trying to do the
fine-tuning.  I followed your direction to create the dataset first, but
when I run the command to fine tune I get an error:

(.venv) Lees-EJ-MacBook-Pro:chesscog leason$ python -m
chesscog.transfer_learning.train

[2023-11-06 15:27:08,679] {train.py:46} INFO - Starting training for
occupancy_classifier

[2023-11-06 15:27:08,716] {train.py:55} INFO - Starting training in
/Users/leason/src/pawntificator/chesscog/runs/transfer_learning/occupancy_classifier

[2023-11-06 15:27:08,716] {train.py:61} WARNING - The folder
/Users/leason/src/pawntificator/chesscog/runs/transfer_learning/occupancy_classifier
already exists and will be overwritten by this run

Traceback (most recent call last):

  File ***@***.***/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py",
line 196, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File ***@***.***/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py",
line 86, in _run_code

    exec(code, run_globals)

  File
"/Users/leason/src/pawntificator/chesscog/chesscog/transfer_learning/train.py",
line 47, in <module>

    _train_model(model_type)

  File
"/Users/leason/src/pawntificator/chesscog/chesscog/transfer_learning/train.py",
line 38, in _train_model

    train_model(cfg, run_dir, model, is_inception,

  File
"/Users/leason/src/pawntificator/chesscog/chesscog/core/training/train.py",
line 80, in train_model

    dataset = build_dataset(cfg, Datasets.TRAIN)

  File
"/Users/leason/src/pawntificator/chesscog/chesscog/core/dataset/dataset.py",
line 70, in build_dataset

    dataset = torchvision.datasets.ImageFolder(root=URI(cfg.DATASET.PATH) /
mode.value,

  File
"/Users/leason/src/pawntificator/.venv/lib/python3.10/site-packages/torchvision/datasets/folder.py",
line 309, in __init__

    super().__init__(

  File
"/Users/leason/src/pawntificator/.venv/lib/python3.10/site-packages/torchvision/datasets/folder.py",
line 145, in __init__

    samples = self.make_dataset(self.root, class_to_idx, extensions,
is_valid_file)

  File
"/Users/leason/src/pawntificator/.venv/lib/python3.10/site-packages/torchvision/datasets/folder.py",
line 189, in make_dataset

    return make_dataset(directory, class_to_idx, extensions=extensions,
is_valid_file=is_valid_file)

  File
"/Users/leason/src/pawntificator/.venv/lib/python3.10/site-packages/torchvision/datasets/folder.py",
line 102, in make_dataset

    raise FileNotFoundError(msg)

FileNotFoundError: Found no valid file for the classes empty, occupied.
Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff,
.webp


I've spent a while trying to debug this but I'm not sure what is wrong.
The training images are in data/transfer_learning/images/train and the
.json files are there with the contents as described in the paper.  The
error on the last line makes me feel like I've missed a step somehow.  Was
I supposed to copy some training data for "empty" and "occupied" squares?
I'm pretty sure the occupancy and piece classifier models are right, but
maybe I'm missing something there?
[image: image.png]

Lee

**Comment by georg-wolflein** [comment]
Hi Lee, can you double-check that you ran `python -m chesscog.transfer_learning.create_dataset`? (see my original comment above)

PS: I couldn't see the attached image.

**Comment by leason** [comment]
I feel silly - I was putting the fine tune training images in the wrong
directory, but your question forced me to add debug lines to the code to
figure that out.  The training now seems to be working, although my macbook
crashed on the first attempt.  I'm trying to do this on a 2019 intel mac
pro with an AMD GPU which means it's all being done on the CPU.  Needless
to say it's slow (first training took over two hours before it crashed the
whole mac).  Worst case scenario I can move all this up to an AWS based
machine, do the training there, and then pull down the files locally.

Thank you!
